id: A2C272AEC
title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
type: translation
pechas:
- I97451ED8
- I7761E61E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:02:03.752492
  last_modified_at: 2023-01-04 12:02:03.752503
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I97451ED8/3465: 8BC9
  I7761E61E/9999: 8BC9
